include: package:sizzle_lints/lints.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    invalid_annotation_target: ignore
    type_annotate_public_apis: ignore ignore
  exclude:
    - "lib/src/core/localization/generated/**"

dart_code_metrics:
  extends:
    - package:sizzle_lints/dcm.yaml
